const modelTimes=["08:45","09:45","10:45","11:45","12:45","13:45","15:45"];const labels=["Pre-open","Anchor","Reaction","Follow-through","Midday","Afternoon","Pre-close"];const timezone="America/New_York";
const esc=v=>String(v??"--").replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function minutes(hhmm){const [h,m]=hhmm.split(":").map(Number);return h*60+m}
function getNewYorkTime(){return new Intl.DateTimeFormat("en-US",{timeZone:timezone,hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date())}
function setText(id,value){const e=document.querySelector(id);if(e)e.textContent=value}
function renderTimeline(){document.querySelector("#timeline").innerHTML=modelTimes.map((t,i)=>`<div class="time"><strong>${t}</strong><span>${labels[i]}</span></div>`).join("")}
function renderSummary(data){const stats=data.summary||{},sessions=data.sessions||[],events=data.market_events||[];setText("#dataSource",`Python engine · ${data.source_file||"research dataset"}`);setText("#tradeCount",stats.trades??0);setText("#winRate",`${Number(stats.win_rate??0).toFixed(2)}%`);setText("#netR",`${Number(stats.net_r??0).toFixed(2)}R`);setText("#sessionCount",sessions.length);setText("#sessionDataLabel",data.source_file||"demo dataset");
const rows=sessions.map(x=>`<tr><td>${esc(x.date)}</td><td>${Number(x.anchor_high??0).toFixed(2)} / ${Number(x.anchor_low??0).toFixed(2)}</td><td>${esc(x.first_break)}</td><td>${esc(x.first_confirmation)}</td><td>${x.entry==null?"--":Number(x.entry).toFixed(2)}</td><td>${x.target==null?"--":Number(x.target).toFixed(2)}</td><td>${esc(x.outcome)}</td><td>${Number(x.r_multiple??0).toFixed(2)}R</td></tr>`).join("");document.querySelector("#sessionRows").innerHTML=rows||`<tr><td colspan="8">No research sessions found.</td></tr>`;
const erows=events.map(e=>`<tr><td>${esc(e.time)}</td><td>${esc(e.label)}</td><td>${esc(e.liquidity_reference)}</td><td>${esc(e.liquidity_event)}</td><td>${esc(e.break_direction)}</td><td>${esc(e.structure)}</td><td>${e.displacement?"YES":"NO"}</td><td>${esc(e.confirmation)}</td></tr>`).join("");document.querySelector("#eventRows").innerHTML=erows||`<tr><td colspan="8">No market events found.</td></tr>`;
const first=sessions.find(x=>x.outcome!=="no_setup");if(first){setText("#decision",`RESEARCH RESULT · ${String(first.outcome).toUpperCase()} · ${String(first.first_confirmation).toUpperCase()} SETUP`);setText("#direction",String(first.first_confirmation).toUpperCase());setText("#entry",first.entry==null?"--":Number(first.entry).toFixed(2));setText("#invalidation",first.invalidation==null?"--":Number(first.invalidation).toFixed(2));setText("#target",first.target==null?"--":Number(first.target).toFixed(2));}else setText("#decision","RESEARCH · NO CONFIRMED SETUP");
const confirmed=events.find(e=>e.confirmation&&e.confirmation!=="none");const latest=confirmed||events.find(e=>e.time!=="09:45");if(latest){setText("#breakState",String(latest.break_direction||"none").toUpperCase());setText("#structureState",String(latest.structure||"neutral").toUpperCase());setText("#liquidityState",String(latest.liquidity_event||"none").replaceAll("_"," ").toUpperCase());setText("#displacementState",latest.displacement?"YES":"NO");setText("#confirmationState",String(latest.confirmation||"none").toUpperCase())}}
async function loadResearchResults(){try{const r=await fetch("data/demo-results.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);renderSummary(await r.json())}catch(e){setText("#dataSource","Research data unavailable");setText("#decision","RESEARCH DATA ERROR");console.error(e)}}
function updateClock(){const current=getNewYorkTime(),currentMinutes=minutes(current);setText("#clock",`${current} ET`);let active=-1;modelTimes.forEach((t,i)=>{if(currentMinutes>=minutes(t))active=i});setText("#window",active>=0?`${modelTimes[active]} ET · ${labels[active]} window`:"Before model window");document.querySelectorAll(".time").forEach((el,i)=>{el.classList.toggle("active",i===active);el.classList.toggle("past",i<active)})}
renderTimeline();updateClock();loadResearchResults();setInterval(updateClock,15000);